from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ResumeAnalyzer(models.Model):

    #we set a foreign key to the User table - every analysis belongs to one user only
    #on_delete = models.CASCADE => we delete one user, we delete the analyses belonging to the user
    #related_name = 'analyses' will help us with query readbility
    #The User model is the model that stores user info (id, username, password, email, token), generated by django
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='analyses')

    resume_file = models.FileField(upload_to='resumes/', null=True, blank=True)
    resume_text = models.TextField(blank= True)

    job_text = models.TextField(blank = True)

    match_score = models.IntegerField(blank = True, null = True)
    matched_keywords = models.JSONField(blank = True, null = True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):

        return f"Anaysis {self.id} - match score = {self.match_score}"