from rest_framework import serializers
from .models import ResumeAnalyzer
from .services.analysis import analyze_resume

class ResumeAnalyzerSerializer(serializers.ModelSerializer):
    
    class Meta:
        model = ResumeAnalyzer
        fields = ['id', 'resume_text', 'job_text', 'match_score', 'matched_keywords', 'created_at']
        read_only_fields = ['id', 'match_score', 'matched_keywords', 'created_at'] #we mark them as read only so they are not expected in the request body, as they are computed by us or generated by django/the system
    
    def validate(self, data): #we are moving request body data validation from view to serializer; this method runs when we call serializer.is_valid()

        resume = data.get('resume_text')
        job = data.get('job_text')

        if not resume or not job:

            raise serializers.ValidationError('resume_text and job_text are required')
        
        return data
    
    def create(self, validated_data): #we are moving object creation from view to serializer; this method runs when we call serializer.save()

        resume_text = validated_data['resume_text']
        job_text = validated_data['job_text']

        score, matched_keywords = analyze_resume(resume_text=resume_text, job_text=job_text)

        return ResumeAnalyzer.objects.create(resume_text = resume_text, job_text = job_text, match_score = score, matched_keywords = matched_keywords)


