from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from .models import ResumeAnalyzer
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import (
    ResumeAnalyzerSerializer,
    RegistrationSerializer,
    ResumeUploadSerializer,
    JobDescriptionUploadSerializer,
    AnalyzeResumeSerializer,
)
from .pagination import AnalysisListPagination
from rest_framework.permissions import AllowAny, IsAuthenticated
from .services.parse_pdf import PdfParser
from .services.analysis import ResumeAnalyzerTool
from rest_framework.parsers import MultiPartParser, FormParser

from rest_framework.generics import CreateAPIView, ListAPIView, RetrieveAPIView
from rest_framework.views import APIView

from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator

from .tasks import run_resume_analysis
from celery.result import AsyncResult

from rest_framework import status as http_status


# Create your views here.
def home(request):
    return HttpResponse("The server is up and running")


def ping(request):
    return JsonResponse({"status": 200, "message": "Server is running"})


# WHEN WE USE CLASS BASED VIEWS (but not generic, just APIView), the method inside just be called post or get,
# so django knows what type of request to except, instead of using the api_view decorator
class ResumeUploadView(APIView):

    parser_classes = [MultiPartParser, FormParser]

    def post(self, request):

        serializer = ResumeUploadSerializer(
            data=request.data, context={"request": request}
        )

        serializer.is_valid(raise_exception=True)
        analysis = serializer.save()

        return Response(
            {"analysis_id": analysis.id, "message": "Resume uploaded successfully"},
            status=200,
        )


class JobDescriptionUploadView(APIView):

    parser_classes = [MultiPartParser, FormParser]

    def post(self, request, analysis_id):

        try:
            analysis = ResumeAnalyzer.objects.get(id=analysis_id, user=request.user)
        except ResumeAnalyzer.DoesNotExist:
            return Response({"error": "Not found"}, status=404)

        # because we call the serialzier with the analysis instance, Django calls the .upload() method instead of .create() when we save, replacing the state of the same object
        serializer = JobDescriptionUploadSerializer(
            analysis, data=request.data, context={"request": request}
        )

        serializer.is_valid(raise_exception=True)
        analysis = serializer.save()

        return Response(
            {
                "analysis_id": analysis_id,
                "message": "Job description successfully uploaded",
            },
            status=200,
        )


class AnalyzeResumeView(APIView):

    def get(self, request, analysis_id):

        try:
            analysis = ResumeAnalyzer.objects.get(id=analysis_id, user=request.user)
        except ResumeAnalyzer.DoesNotExist:
            return Response({"error": "Not found"}, status=404)

        if not analysis.resume_text or not analysis.job_text:
            return Response({"error": "Missing data"}, status=400)

        # .delay sends the job to Redis instantly
        task = run_resume_analysis.delay(
            analysis.id
        )  # don t pass the whole object, always pass ids
        serializer = AnalyzeResumeSerializer(analysis)
        # task is a celery AsyncResult object because of .delay()
        # every celery task has an unique id generated by celery itself
        # becuase task is an AsyncResult object, we can access the .id field
        return Response({**serializer.data, "task_id": task.id}, status=200)


class TaskStatusView(APIView):

    def get(self, request, task_id):

        # AsyncResult is a Celery object that tracks the state of a task after it has been sent to the worker
        # task_id → the unique ID Celery assigned when you called .delay(); it will be passed through the url
        # Task state = task_status.state

        # Possible values:

        # PENDING → task not started yet

        # STARTED → worker picked it up

        # SUCCESS → finished successfully

        # FAILURE → crashed with an exception

        # RETRY → being retried

        # Task result (only if finished) = task_status.result

        # If SUCCESS → returns whatever your task returned

        # If FAILURE → returns the exception object

        task_status = AsyncResult(task_id)

        response = {"task_id": task_id, "task_status": task_status.state}

        # default status, task still running or pending
        status = http_status.HTTP_202_ACCEPTED

        if task_status.state == "SUCCESS":
            response["result"] = task_status.result
            status = http_status.HTTP_200_OK

        if task_status.state == "FAILURE":
            response["error"] = task_status.result
            status = http_status.HTTP_400_BAD_REQUEST

        return Response(response, status=status)


class AnalysisListView(ListAPIView):

    serializer_class = ResumeAnalyzerSerializer
    pagination_class = AnalysisListPagination

    filterset_fields = [
        "match_score",
        "created_at",
    ]  # we set that we can filter by match_score and created_at
    ordering_fields = [
        "created_at",
        "match_score",
    ]  # we set that we can order by created_at and match_score
    ordering = ["-created_at"]  # we set default ordering by created_at, descending

    def get_queryset(
        self,
    ):  # we override get_queryset so a user only gets analyses from the table that belong to him
        return ResumeAnalyzer.objects.filter(user=self.request.user)


class AnalysisDetailView(RetrieveAPIView):

    serializer_class = ResumeAnalyzerSerializer

    def get_queryset(self):
        return ResumeAnalyzer.objects.filter(user=self.request.user)


class RegistrationView(CreateAPIView):

    serializer_class = RegistrationSerializer
    permission_classes = [
        AllowAny
    ]  # we override the isAuthenticated global permission because registration has to be public


class LogoutView(APIView):

    def post(self, request):

        request.user.auth_token.delete()
        return Response({"message": "Logged out"}, status=http_status.HTTP_200_OK)
