# Generated by Django 6.0 on 2025-12-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalyzer',
            old_name='resume',
            new_name='resume_text',
        ),
    ]
