# Generated by Django 5.2.7 on 2025-12-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_resumeanalyzer_user_alter_resumeanalyzer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalyzer',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='resumeanalyzer',
            name='resume_text',
            field=models.TextField(blank=True),
        ),
    ]
