# Generated by Django 6.0 on 2025-12-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_resumeanalyzer_resume_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeanalyzer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resumeanalyzer',
            name='job_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalyzer',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumeanalyzer',
            name='matched_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
