# Generated by Django 6.0 on 2026-01-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_alter_resumeanalyzer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalyzer',
            name='status_choice',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
