# Generated by Django 6.0 on 2026-01-02 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_resumeanalyzer_status_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalyzer',
            old_name='status_choice',
            new_name='status',
        ),
    ]
